fail_fast: true
repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: cargo-check
      - id: clippy
  - repo: local
    hooks:
      - id: toml-fmt
        name: Taplo formatting
        entry: taplo format
        description: format all toml files
        args:
          - '--verbose'
          - '--diff'
        language: system
      - id: rust-fmt
        name: Rust formatting
        description: Format files with rustfmt
        entry: cargo +nightly fmt --
        language: system
        files: \.rs$
        args:
          - '-v'
          - '--unstable-features'
          - '--error-on-unformatted'
